### ISSUE TITLE
Building releases with scribe fails due to duplicate modules

### ISSUE THREAD

**Issue by arnomi** [codedge-llc/scribe#7]
Hi,

we recently tried to add scribe to a project and had to remove it again since it broke any release build with distillery. When running a release build distillery fails with

```
==> Release failed, during .boot generation:
        Duplicated modules:
        'Elixir.Inspect.Map' specified in elixir and scribe
        'Elixir.Inspect.List' specified in elixir and scribe
        'Elixir.Inspect.Any' specified in elixir and scribe
```

Is there any known workaround for this?

**Comment by hpopp** [comment]
At the moment the best you can do is disable for prod entirely with `{:scribe, "~> 0.7", only: :dev}`.

I'm thinking of reworking `config :scribe, enable: false` to prevent compilation of the inspect overrides instead of disabling at runtime. This would allow you to still use `Scribe.print/2` in production-- useful for CLI admin reports and such.

**Comment by arnomi** [comment]
Thanks for the quick response.

For us, we actually just used the scribe "functions" and disabled it also in dev since overwriting the inspect behaviour is often too intrusive (for example, you cannot easily copy parts of a structure anymore if it is in table form). So we would definitely welcome this change.

**Comment by hpopp** [comment]
Interesting user feedback, I've been debating whether to make the make the override opt-in instead of opt-out.

The configuration API I have in mind right now:
```elixir
config :scribe, auto_inspect: true
config :scribe, compile_auto_inspect: true

iex> inspect(stuff, scribe: false)
```

Options should be self explanatory. If `scribe: false` was available for inspect, would you be more likely to prefer having scribe enabled by default?
